version: '3.8'

services:

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - ldnet

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    networks:
      - ldnet
      
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - ldnet
      
  redis:
    image: "redis:alpine"
    volumes:
      - ./redis:/data
    networks:
      - ldnet

networks:
  ldnet:
    driver: bridge
